---
title: "R Workshop"
author: "Felix lorenz"
date: '12. Dezember 2022'
amt: "Staatskanzlei"
stelle: "Dienststelle für Statistik"
output: 
  xaringan::moon_reader:
    highlightStyle: github
    highlightlines: true
    highlightSpans: true
    css: ["default","img/styles_x.css"]


---
```{r xaringan-logo, echo=FALSE}
xaringanExtra::use_logo(
  image_url = "./img/tg.jpg"
)
```

```{r xaringan-banner, echo=FALSE}
xaringanExtra::use_banner(
  bottom_center = paste0("\U00A9 ",rmarkdown::metadata$amt),
  top_left = paste0("<h6>",rmarkdown::metadata$amt,"</h6><h7>",rmarkdown::metadata$stelle,"</h7>"),
  bottom_left = rmarkdown::metadata$date,
  exclude = "title-slide"
)
```


```{r xaringan-panelset, echo=FALSE}
xaringanExtra::use_panelset(TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,dpi=300)
options(knitr.duplicate.label = 'allow')
options(htmltools.dir.version = FALSE)

```



```{r xaringan-tachyons, echo=FALSE}
xaringanExtra::use_tachyons()
```



```{r child='rmd/intro.Rmd'}
```
---
```{r child='rmd/mindset.Rmd'}
```
---
```{r child='rmd/tidyverse.Rmd'}
```
---
```{r child='rmd/daten_einlesen.Rmd'}
```
---
```{r child='rmd/magrittr.Rmd'}
```
---
```{r child='rmd/tidy_data.Rmd'}
```
---
```{r child='rmd/tidyr.Rmd'}
```
---
```{r child='rmd/dplyr.Rmd'}
```
---
```{r child='rmd/stringr.Rmd'}
```
---
```{r child='rmd/lubridate.Rmd'}
```
---
```{r child='rmd/listen.Rmd'}
```
---
```{r child='rmd/conditional_statements.Rmd'}
```
---
```{r child='rmd/loops_apply.Rmd'}
```
---
```{r child='rmd/funktionen.Rmd'}
```
---
```{r child='rmd/ggplot.Rmd'}
```
---

```{r child='rmd/daten_einlesen2.Rmd'}
```
---

```{r child='rmd/excel_schreiben.Rmd'}
```
---


```{r child='rmd/rest_apis.Rmd'}
```
---

```{r child='rmd/databases.Rmd'}
```
---







